name: Schedule Test

on:
  schedule:
    - cron: "*/5 * * * *"
      timezone: "Asia/Seoul"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Test scheduler
        run: |
          echo "Scheduler works!"
          date
